[window]
opacity = 1
title = ""
dynamic_title = false
option_as_alt = "Both"
decorations = "Buttonless"

[window.dimensions]
columns = 210
lines = 55

[window.padding]
y = 5
x = 5

[window.position]
x = 435
y = 180

[font]
size = 15

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[[colors.indexed_colors]]
color = "#FAB387"
index = 16

[[colors.indexed_colors]]
color = "#F5E0DC"
index = 17

[colors.bright]
black = "#585B70"
blue = "#89B4FA"
cyan = "#29C3DE"
green = "#A6E3A1"
magenta = "#F5C2E7"
red = "#F38BA8"
white = "#A6ADC8"
yellow = "#F9E2AF"

[colors.cursor]
cursor = "#FF78C6"
text = "#1E1E2E"

[colors.dim]
black = "#45475A"
blue = "#89B4FA"
cyan = "#29C3DE"
green = "#A6E3A1"
magenta = "#F5C2E7"
red = "#F38BA8"
white = "#BAC2DE"
yellow = "#F9E2AF"

[colors.hints.end]
background = "#A6ADC8"
foreground = "#1E1E2E"

[colors.hints.start]
background = "#F9E2AF"
foreground = "#1E1E2E"

[colors.normal]
black = "#45475A"
blue = "#89B4FA"
cyan = "#29C3DE"
# green = "#A6E3A1"
green = "#A6E3A1"
magenta = "#F5C2E7"
red = "#F38BA8"
white = "#BAC2DE"
yellow = "#F9E2AF"

[colors.primary]
background = "#1E1E2E"
bright_foreground = "#CDD6F4"
dim_foreground = "#CDD6F4"
foreground = "#CDD6F4"

[colors.search.focused_match]
background = "#A6E3A1"
foreground = "#1E1E2E"

[colors.search.matches]
background = "#A6ADC8"
foreground = "#1E1E2E"

[colors.selection]
background = "#F5E0DC"
text = "#1E1E2E"

[[keyboard.bindings]]
key = "m"
mods = "Control"
action = "IncreaseFontSize"

[[keyboard.bindings]]
key = "m"
mods = "Control|Shift"
action = "DecreaseFontSize"

[[keyboard.bindings]]
key = "0"
mods = "Control"
action = "ResetFontSize"

[[keyboard.bindings]]
chars = "\u001BB"
key = "J"
mods = "Alt"
mode = "AppCursor"

[[keyboard.bindings]]
chars = "\u001BF"
key = "K"
mods = "Alt"
mode = "AppCursor"

[[keyboard.bindings]]
chars = "\u001BOF"
key = "L"
mods = "Alt"
mode = "AppCursor"

[[keyboard.bindings]]
chars = "\u001BOH"
key = "H"
mods = "Alt"
mode = "AppCursor"

[[keyboard.bindings]]
chars = "\u001BF"
key = "ArrowRight"
mods = "Alt"
mode = "AppCursor"

[[keyboard.bindings]]
chars = "\u001BB"
key = "ArrowLeft"
mods = "Alt"
mode = "AppCursor"

[[keyboard.bindings]]
key = "Tab"
mods = "Control"
chars = "\u001b[27;5;9~"

[[keyboard.bindings]]
key = "Tab"
mods = "Control|Shift"
chars = "\u001b[27;6;9~"
